name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: BOE-ChatBot-BackEnd     
  PYTHON_VERSION: '3.11' 
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  STARTUP_COMMAND: 'uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload'

on:
  push:
    branches: 
      - pro
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : Python checkout
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Building web app
        uses: azure/appservice-build@v2

      - name: Deploy web App using GH Action azure/webapps-deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          startup-command: ${{ env.STARTUP_COMMAND }}

