name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: BOE-ChatBot-BackEnd  # set this to the name of your Azure Web App
  AZURE_RESOURCE_GROUP_NAME: BOE-ChatBot   # set this to the name of your Azure Resource Group
  PYTHON_VERSION: '3.11'              # set this to the Python version to use

on:
  push:
    branches: [ "pro" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip the application for deployment
        run: |
          zip -r python-app.zip . -x "venv/*" "*.git/*" "*.github/*"

      - name: Upload deployment package
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: python-app.zip

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download deployment package from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app
          path: .

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: python-app.zip

      - name: Configure FastAPI startup command in Azure Web App
        run: |
          az webapp config set --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME }} --startup-file "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
