name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: BOE-ChatBot-BackEnd  # set this to the name of your Azure Web App
  AZURE_RESOURCE_GROUP_NAME: BOE-ChatBot   # set this to the name of your Azure Resource Group
  PYTHON_VERSION: '3.11'              # set this to the Python version to use

on:
  push:
    branches: 
      - pro
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip the application for deployment
        run: |
          zip -r python-app.zip . -x "venv/*" "*.git/*" "*.github/*"

      - name: Upload deployment package
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: python-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Cloning repository
        uses: actions/checkout@v4

      - name: Building web app
        uses: azure/appservice-build@v3

      - name: Deploying web app to Azure
        uses: azure/webapps-deploy@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}

      - name: Configure FastAPI startup command in Azure Web App
        run: |
          az webapp config set --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME }} --startup-file "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
