name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: BOE-ChatBot-BackEnd  
  AZURE_RESOURCE_GROUP_NAME: BOE-ChatBot   
  PYTHON_VERSION: '3.11' 
  WORKING_DIRECTORY: '.'     
  STARTUP_COMMAND: 'uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload'

on:
  push:
    branches: 
      - pro
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : Python checkout
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: 
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          mask-inputs: false
          general-settings-json: '{"linuxFxVersion": "PYTHON|${{ env.PYTHON_VERSION }}"}' #'General configuration settings as Key Value pairs'
      - name: Deploying web app to Azure
        uses: azure/webapps-deploy@v2
        with:
          publish-profile : ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.WORKING_DIRECTORY }}
          startup-command: ${{ env.STARTUP_COMMAND }}
          
      - name: Azure logout
        run: |
          az logout

