name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: BOE-ChatBot-BackEnd  # set this to the name of your Azure Web App
  AZURE_RESOURCE_GROUP_NAME: BOE-ChatBot   # set this to the name of your Azure Resource Group
  PYTHON_VERSION: '3.11' 
  WORKING_DIRECTORY: '.'        # set this to the path to your path of working directory inside github repository, defaults to the repository root
  STARTUP_COMMAND: 'uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload'

on:
  push:
    branches: 
      - pro
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : Python checkout
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploying web app to Azure
        uses: azure/webapps-deploy@v2
        with:
          publish-profile : ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.WORKING_DIRECTORY }}
          startup-command: ${{ env.STARTUP_COMMAND }}

